spring.application.name=bankcards

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_rest
spring.datasource.username=bank_user
spring.datasource.password=bank_pass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.drop-first=true

spring.liquibase.change-log=classpath:db/migration/db.changelog-master.yaml

security.jwt.secret=YzA0Y2M4ZGNkNmU3M2Q2M2Y2MDMwMzM3YjBhNWQwNzU4NWE1ZmY4NmM5NDU0NmQxODhjODJkYzQwY2MwNjQ3MQ==
security.jwt.expiration-ms=3600000
security.card.encryption-key=YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg=
